### Site
repository: ttasc/ttasc/tree/resume
favicon: images/favicon.ico

### Content configuration version
version: 2

### Personal info
name: Nguyễn Lê Tiến Triển
title: Seeking Internship or Employment
email: nltt@tuta.io
# website:

### Dark Mode (true/false/never)
darkmode: never

### Social links
github_username:  ttasc
stackoverflow_username: "29622488"
linkedin_username: ttasc
# twitter_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username:
# orcid_username:

### Additional icon links
# additional_links:
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

#####################
### About Section ###
#####################
about_title: About
about_profile_image: images/profile.jpeg
about_content: |
  Hi, I'm Trien! 👋

  A proactive undergraduate in Networking with a strong interest in backend programming and developing network-driven applications. Continuously expanding expertise in networking and cybersecurity through dedicated learning and personal projects. Actively seeking practical experiences to complement academic knowledge and accelerate growth. Currently pursuing internship or junior opportunities to apply my technical skills, contribute value, and develop professionally within a supportive environment.

##############
### Resume ###
##############
content:
  #######################
  ### Work Experience ###
  #######################
  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Information Technology Center of Saigon University
        sub_title: Intern System Administrator
        caption: October 2024 - April 2025
        link: ttcntt.sgu.edu.vn
        link_text: ttcntt.sgu.edu.vn
        quote: >
          IT Support / System Administrator Intern with hands-on experience in Linux server deployment, web hosting management, and system troubleshooting. Skilled in supporting IT infrastructure, managing web services, and assisting users in resolving technical issues. Familiar with Docker, WordPress, and basic backend development, with a strong foundation in both Windows and Linux environments.
        description: |
          <mark>Linux Server</mark> <mark>Docker</mark> <mark>Go/Bash/Python</mark> <mark>FastPanel</mark>

          - Managed and maintained Linux-based servers (Debian) to support internal systems and academic platforms
          - Deployed and configured V-SAT examination system, ensuring stable and secure operation
          - Administered web hosting environment using FastPanel, including domain, database, and user management
          - Implemented and maintained WordPress websites using Docker, improving deployment consistency and scalability
          - Built a lightweight internal web application using Golang and HTMX to display announcements and system information
          - Performed system monitoring, basic troubleshooting, and service configuration on both Linux and Windows environments

  #################
  ### Education ###
  #################
  - title: Education
    layout: list
    content:
      - layout: left
        title: Saigon University (SGU)
        caption: 2022 - Ongoing
        sub_title: BSc Computer Engineering
        # quote: >
        #
        description: |
          During my time at SGU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  ################
  ### Projects ###
  ################
  - title: Projects
    layout: list
    content:

      #############
      ### Quizz ###
      #############
      - layout: top-middle
        border: weak
        title: Quizz
        sub_title: Founder & Primary Backend Developer
        link: github.com/ttasc/Quizz
        # link_text: visit
        quote: >
          Quiz management system for schools, teachers or simply want to organize a quiz test.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./prjimg/Quizz.png" />
          </div>

          I started this project as a way to learn about **Java** and **OOP**. In its early days, it was just a simple CLI software without a database. With the collaboration of my friends at university, I continued to develop it into a beautiful **GUI** application that can be used over a **LAN**. Although it is not yet production-ready due to existing bugs and incomplete features (*primarily within the GUI processing layer*), I successfully developed and solidified the core *backend* functionality, ensuring its smooth operation.

          <mark>JavaFX</mark> <mark>Socket</mark> <mark>Multithreading</mark> <mark>MariaDB/MySQL</mark> <mark>Networking</mark> <mark>Excel Processing</mark>

      ###################
      ### Go Projects ###
      ###################
      - layout: top-middle
        border: weak
        title: Go Projects
        sub_title: Primary Developer
        # link: github.com/ttasc
        # link_text: visit
        additional_links:
          - title:  sgublogsite
            icon:   fab fa-github
            url:    github.com/ttasc/sgublogsite
          - title:  craftt
            icon:   fab fa-github
            url:    github.com/ttasc/craftt
        quote: >
          These are projects written in Go.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./prjimg/sgublogsite.png" />
          </div>

          **[sgublogsite](https://github.com/ttasc/sgublogsite)**: During my internship as a System Administrator, alongside core responsibilities of deploying, monitoring, and maintaining requested services, I embarked on developing a school news website. Driven by a desire to learn, this project provided me with valuable experience in: web development process (outside my expertise), practical Go programming and library usage, and foundational web security principles. A website with simple technology for stability and security. However, due to limitations in frontend implementation, the project remains incomplete. I made the decision to discontinue development to focus on new projects better aligned with my core competencies and career goals.
            - <mark>Go</mark> <mark>Chi</mark> <mark>HTMX</mark> <mark>MariaDB/MySQL</mark>

          <br/>

          <div align="center">
            <img align="center" width="70%" src="./prjimg/craftt.png" />
          </div>
          **[craftt](https://github.com/ttasc/craftt)** was born from observing my brother's struggle to manage our Proxmox-hosted Minecraft server due to limited terminal/SSH knowledge. This web app simplifies server control with one-click start/stop, live log viewing, and command execution. Beyond solving accessibility issues, it became a learning platform where I mastered Linux container process control, built secure TLS-enabled Go servers, and engineered real-time WebSocket data streaming for log interactions.
            - <mark>Go</mark> <mark>Process handling</mark> <mark>WebSocket</mark> <mark>TLS</mark>

      #############
      ### anett ###
      #############
      - layout: top-middle
        border: weak
        title: anett
        sub_title: Primary Developer
        link: github.com/ttasc/anett
        # link_text: visit
        quote: >
          Dockerized Local Service Deployment Toolkit
        description: |
          This small project started simply because I wanted to learn Docker. It's not a real-world tool, but it helps my university friends quickly set up local services like DNS or FTP for study purposes. Through this project, I've improved my shell scripting skills and finally understood Docker concepts hands-on.

          <mark>Linux Server</mark> <mark>Docker</mark> <mark>Shell</mark> <mark>TUI</mark> <mark>Networking</mark>

      ################
      ### Dotfiles ###
      ################
      - layout: top-middle
        title: Dotfiles
        sub_title: Explorer & Developer
        link: github.com/ttasc/Dotfiles
        # link_text: visit
        quote: >
          My Workflow Optimization: Minimal, performance-focused. Extremely fast and small without sacrificing convenience.
        description: |
          <div align="center">
            <img align="center" width="70%" src="./prjimg/Dotfiles.png" />
          </div>
          I started exploring the world of Linux when I first entered high school. After a period of using Windows and gaining some experience in troubleshooting and problem-solving, I decided to switch to a new home - GNU/Linux. Through my journey with multiple Linux distributions and continuous exploration, I gained a deeper understanding of many computer-related concepts, including hardware, networking, and how an operating system works. I also started learning programming and created my own development environment on Linux, which is my Dotfiles.

          <mark>Administration</mark> <mark>Troubleshooting</mark> <mark>Scripting</mark> <mark>Networking</mark> <mark>Modifying OSS</mark> <mark>Home server</mark>

  ###############
  ### Skills ####
  ###############
  - title: Skills
    layout: list
    content:
      - layout: right
        sub_title: Soft Skills
        caption: Problem-solving, communication and interpersonal skills. Effective time management and teamwork.
        description: |
          - **System Administration**
            - Networking, Scripting, Monitoring, Active Directory, Cloud Computing
          - **Hardware**
            - System Building, Maintenance, Prototyping
          - **Systems**
            - Debian/Redhat/Arch - based Linux, Proxmox
            - Windows 10/11, Windows Server
          - **Software (Backend)**
            - Docker, MySQL/MariaDB, Apache, NGINX
          - **Software (Other)**
            - Git, Vim, Make, Eclipse, Unix Tools,...
          - **Languages**
            - C, C++, Java, Go, Python
            - Bash, Powershell, SQL

  ###############
  ### Hobbies ###
  ###############
  - title: When I’m Not At My Desk
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:

      <img align="right" height="100" src="/ttasc/images/cooking.gif"/>

      - Cooking (really love cooking 🔥)
      - Traveling
      - Reading
      - Linux Ricing

### Footer
footer_show_references: true
references_title: Ho Chi Minh, Viet Nam

### Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
