### Site
repository: sproogen/resume-theme
favicon: images/favicon.ico

### Content configuration version
version: 2

### Personal info
name: Nguyễn Lê Tiến Triển
title: Intern Network System Administrator
email: nltt@tuta.io
# website:

### Dark Mode (true/false/never)
darkmode: false

### Social links
github_username:  TTlaugh
stackoverflow_username: "29622488"
linkedin_username: TTlaugh
# twitter_username:
# dribbble_username:
# facebook_username:
# flickr_username:
# instagram_username:
# xing_username:
# pinterest_username:
# youtube_username:
# googleplus_username:
# orcid_username:

### Additional icon links
# additional_links:
# - title: itsgoingto.be
#   icon: fas fa-globe
#   url: https://www.itsgoingto.be
# - title: another link
#   icon: font awesome brand icon name (eg. fab fa-twitter) (https://fontawesome.com/icons?d=gallery&m=free)
#   url: Link url (eg. https://google.com)

### About Section
about_title: About Me
about_profile_image: images/profile.jpeg
about_content: |
  Hi, my name's Trien and I'm a intern network system administrator. As well as administrating systems I also have experience making software. I hope to work in a challenging and engaging environment where I can contribute my skills towards a meaningful goal.

content:
  - title: Projects
    layout: list
    content:
      - layout: top-middle
        border: weak
        title: QMgr
        sub_title: Founder & Primary Developer
        link: https://github.com/TTlaugh/QMgr
        # link_text: visit
        quote: >
          Quiz management system for schools, teachers or simply want to organize a quiz test.
        description: |
          I started this project as a way to learn about **Java** and **OOP**. In its early days, it was just a simple CLI software without a database. With the collaboration of my friends at university, I continued to develop it into a beautiful **GUI** application that can be used over a **LAN**.

          <mark>JavaFX</mark> <mark>Socket</mark> <mark>Multithreading</mark> <mark>MariaDB/MySQL</mark> <mark>Networking</mark>
      - layout: top-middle
        border: weak
        title: anett
        sub_title: Founder & Primary Developer
        link: https://github.com/TTlaugh/anett
        # link_text: visit
        quote: >
          System administration project: Terminal User Interface (TUI) tool that automatically install and configure services on linux server using docker e.g. DNS, FTP, Web,...
        description: |
          The idea behind this project was to simplify and make the process of setting up and configuring network services more user-friendly. This TUI tool has made that vision a reality. Through my teacher, I gained a lot of valuable knowledge about network system administration, and by working on this project, I was able to solidify my understanding of those concepts.

          <mark>Linux Server</mark> <mark>Docker</mark> <mark>Shell</mark> <mark>TUI</mark> <mark>Networking</mark>
      - layout: top-middle
        title: Dotfiles
        sub_title: Explorer & Developer
        link: https://github.com/TTlaugh/Dotfiles
        # link_text: visit
        quote: >
          My Linux Dotfiles: Minimal, performance-focused. Extremely fast and small without sacrificing convenience.
        description: |
          I started exploring the world of Linux when I first entered high school. After a period of using Windows and gaining some experience in troubleshooting and problem-solving, I decided to switch to a new home - GNU/Linux. Through my journey with multiple Linux distributions and continuous exploration, I gained a deeper understanding of many computer-related concepts, including hardware, networking, and how an operating system works. I also started learning programming and created my own development environment on Linux, which is my Dotfiles.

          <mark>Administration</mark> <mark>Troubleshooting</mark> <mark>Scripting</mark> <mark>Home server</mark>

  - title: Skills
    layout: list
    content:
      - layout: right
        sub_title: Soft Skills
        caption: Good communication and interpersonal skills. Effective time management and teamwork. Patient, sociable, friendly.
        description: |
          - **System Administration**
            - Networking, Scripting, Monitoring, Security, Active Directory, Cloud Computing
          - **Hardware**
            - System Building, Maintenance, Prototyping
          - **Systems**
            - Debian - Redhat - Arch based Linux, Proxmox
            - Windows 10/11, Windows Server
          - **Software (Backend)**
            - Docker, MySQL/MariaDB, Apache, NGINX, IIS
          - **Software (Other)**
            - Git, Vim, Eclipse, OSS,...
          - **Languages**
            - C, C++, Java, GO, Python
            - Bash, Powershell, SQL

  - title: Work Experience
    layout: list
    content:
      - layout: left
        title: Information Technology Center of Saigon University
        sub_title: Intern Network System Administrator
        caption: October 2024 - Present
        link: https://ttcntt.sgu.edu.vn/
        link_text: ttcntt.sgu.edu.vn
        quote: >
          Every modern university needs its networks properly administered and Saigon University is no exception.
        description: |
          <mark>Linux Server</mark> <mark>Windows AD</mark> <mark>Bash/PowerShell</mark> <mark>Docker</mark>

          - Gained on the job experience with industry standard software and practices
          - Developed tools and utilities for application deployment and monitoring
          - Provide top-level technical support to university students and staff

  - title: Education
    layout: list
    content:
      - layout: left
        title: Saigon University (SGU)
        caption: 2022 - Ongoing
        sub_title: BSc Computer Engineering
        # quote: >
        #
        description: |
          During my time at SGU I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thouroughly enjoyed my time as university and learnt a lot about a healthy work life balance.

  - title: When I’m Not At My Desk
    layout: text
    content: |
      Alongside my interests in networks and software engineering some of my other interests and hobbies are:

      <img align="right" height="150" src="/TTlaugh/images/cooking.gif"/>

      - Cooking (really love cooking!)
      - Traveling
      - Gaming (seft-host all my games server on my home server)
      - Linux Ricing

### Footer
footer_show_references: true
references_title: Ho Chi Minh, Viet Nam

### Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
